[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# 🔥 ADICIONE ESSA SEÇÃO ABAIXO PARA O VITE FUNCIONAR:
[dev]
  command = "npm run dev"   # Comando que inicia o seu Vite
  targetPort = 5173         # Porta padrão que o Vite usa localmente
  port = 8888               # Porta que você vai acessar no navegador

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200